### ISSUE TITLE
Replace UMD Wrapper with Browserify build step

### ISSUE THREAD

**Issue by gustavnikolaj** [gustavnikolaj/expect-the-unexpected#1]
Like https://github.com/sunesimonsen/unexpected/blob/master/Makefile#L10

**Comment by sunesimonsen** [comment]
MagicPen is probably a better example: https://github.com/sunesimonsen/magicpen/blob/master/package.json#L17

**Comment by sunesimonsen** [comment]
Thinking about it, Browserify might not be the best choice after all as Unexpected needs to be a peer dependency. I would leave as it is right now.

**Comment by Munter** [comment]
You can still keep browserify as a dev dependency and release the compiled code if you're into that

**Comment by gustavnikolaj** [comment]
The pro of having a browserified build and unexpected as a real depencency is that unexpected is built into the compiled code. Meaning that you can do your shiftover in two steps given the following package.json:
```
{
  ...
  "devDependencies": {
    "expect.js": "x"
  },
  ...
}
```

```diff
- "expect.js": "x"
+ "expect-the-unexpected": "x"

- "expect-the-unexpected": "x"
+ "unexpected": "x"
```

That is a very clear and straight forward path.

The disadvantage to that approach, is that you cannot update unexpected to another version than the one bundled with "expect-the-unexpected", which means that we need to update this package whenever unexpected is updated. And that is inconvenient.

Currently, we rely on unexpected being a dependency of it's own and to be included manually if it's outside a common.js environment. That should be documented in the README if we choose to stick to that.

**Comment by gustavnikolaj** [comment]
The diff for the peerDepencency upgrade path is:

```diff
- "expect.js": "x"
+ "expect-the-unexpected": "x"
+ "unexpected": "x"

- "expect-the-unexpected": "x"
```

Which might be even better actually.

**Comment by gustavnikolaj** [comment]
@sunesimonsen, I remember us discussing this, but I don't remember the conclusion.

**Comment by gustavnikolaj** [comment]
We dropped the idea, and went with the peerDependency and umd wrapper in the file instead.
